style_edition = "2024"
max_width = 80
hard_tabs = true
tab_spaces = 4
newline_style = "Unix"
use_try_shorthand = true
# only work on nightly
# wrap_comments = true
# imports_layout = "HorizontalVertical"
# group_imports = "StdExternalCrate"
# imports_granularity = "Module"
